name: genome
description: "Genome â€“ Gene Analysis Flutter App (Mobile & Desktop)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  http: 0.13.6
  file_picker: ^10.3.6
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  share_plus: ^7.2.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  image_picker: ^1.2.1
  csv: ^6.0.0
  pdf: ^3.11.3
  open_file: ^3.5.10
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ðŸ‘‡ Add your assets here
  assets:
    - assets/images/dna_bg.png
    - assets/images/genora_logo.png
    - assets/images/delete_account.png
    - assets/images/login_art.png
    - assets/images/google_logo.png
    - assets/images/facebook_logo.png
    - assets/images/signup_art.png
    - assets/images/hospital_logo.png
    - assets/images/aboveName.png
    - assets/images/aboveTreatment.png

    
    # Add more assets later like:
    # - assets/icons/
    # - assets/fonts/

  # If you want custom fonts later:
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
  #       - asset: assets/fonts/Cairo-Bold.ttf
  #         weight: 700
